/**
 * V1.0.2 五张报表字段与演示数据
 * 字段来源（只读）：飞书表 IK6EsX575h6b4utKaOMcz2IYnbd · revision 239
 */
(function () {
  const thumb = "";

  const quoteCols = [
    { key: "quoteNo", label: "报价单号", type: "docLink" },
    { key: "customerName", label: "客户名称" },
    { key: "customerNo", label: "客户编号" },
    { key: "factoryNo", label: "厂商编号" },
    { key: "factoryName", label: "厂商名称" },
    { key: "thumb", label: "产品图片", type: "thumb" },
    { key: "productNo", label: "产品编号" },
    { key: "factoryItemNo", label: "出厂货号" },
    { key: "customerItemNo", label: "客户货号" },
    { key: "productName", label: "产品名称" },
    { key: "orderStatus", label: "订单状态", type: "status" },
    { key: "packQty", label: "内盒/外箱装量" },
    { key: "quoteCartons", label: "报价箱数", type: "num" },
    { key: "totalQty", label: "总数量", type: "num" },
    { key: "currency", label: "币种" },
    { key: "purchasePrice", label: "进货价", type: "amount" },
    { key: "exFactoryPrice", label: "出厂价", type: "amount" },
    { key: "quotePrice", label: "报出价格", type: "amount" },
    { key: "amount", label: "总金额", type: "amount" },
    { key: "profit", label: "利润", type: "profit" },
    { key: "productSpec", label: "产品规格" },
    { key: "packSpec", label: "包装规格" },
    { key: "cartonSpec", label: "外箱规格" },
    { key: "volume", label: "体积/材积" },
    { key: "cartonWeight", label: "外箱毛/净重" },
    { key: "productWeight", label: "产品毛/净重" },
    { key: "color", label: "产品颜色" },
    { key: "colorEn", label: "英文颜色" },
    { key: "cert", label: "产品认证" },
    { key: "brand", label: "产品品牌" },
    { key: "material", label: "中文材质" },
    { key: "materialEn", label: "英文材质" },
    { key: "notes", label: "注意事项" },
    { key: "func", label: "功能说明" },
  ];

  const sizeKeys = ["productSpec", "packSpec", "cartonSpec", "volume", "cartonWeight", "productWeight"];
  const attrKeys = ["color", "colorEn", "cert", "brand", "material", "materialEn", "notes", "func"];
  const specTail = {
    productSpec: "60×60×60",
    packSpec: "60×60×60",
    cartonSpec: "60×60×60",
    volume: "0.06(cbm)/2.258(cuft)",
    cartonWeight: "11/10(kg)",
    productWeight: "23/21(kg)",
    color: "蓝色",
    colorEn: "Blue",
    cert: "ACD",
    brand: "Chanel",
    material: "金属",
    materialEn: "Metal",
    notes: "阿斯顿法国红酒看来",
    func: "立刻脚后跟范德萨",
  };

  window.DYJ_REPORTS = {
    quote: {
      key: "quote",
      file: "01-报价数据报表.html",
      title: "报价数据报表",
      source: "销售报价单",
      note: "表列 34 项，对照飞书「报价数据」分组表头。默认状态勾选「报价中」。点报价单号跳转原单。",
      filters: [
        { placeholder: "报价单号" },
        { placeholder: "客户编号 / 名称" },
        { placeholder: "产品编号 / 名称 / 货号" },
        { placeholder: "厂商编号 / 名称" },
        { type: "select", options: ["币种（全部）", "RMB", "USD"] },
      ],
      statusLabel: "订单状态（多选）",
      statusOptions: [
        { label: "报价中", checked: true },
        { label: "已转订货", checked: false },
        { label: "草稿", checked: false },
        { label: "作废", checked: false },
      ],
      groups: [
        { name: "单据主信息", keys: ["quoteNo", "customerName", "customerNo"] },
        { name: "厂商信息", keys: ["factoryNo", "factoryName"] },
        { name: "产品主信息", keys: ["thumb", "productNo", "factoryItemNo", "customerItemNo", "productName", "orderStatus"] },
        { name: "数量及价格", keys: ["packQty", "quoteCartons", "totalQty", "currency", "purchasePrice", "exFactoryPrice", "quotePrice", "amount", "profit"] },
        { name: "尺寸重量", keys: sizeKeys },
        { name: "其他属性", keys: attrKeys },
      ],
      columns: quoteCols,
      rows: [
        { quoteNo: "SQ202608130000000015", customerName: "宣城", customerNo: "CP00001357", factoryNo: "M00000076", factoryName: "测试一下", thumb, productNo: "DY2026081103", factoryItemNo: "0056565-0", customerItemNo: "0056565-0", productName: "(勿动)测试只有小图，没有大图", orderStatus: "报价中", packQty: "2/36(pcs)", quoteCartons: 1, totalQty: 1, currency: "RMB", purchasePrice: "22.00", exFactoryPrice: "11.00", quotePrice: "11.00", amount: "11.00", profit: "-11.00", ...specTail },
        { quoteNo: "SQ202608130000000014", customerName: "海淀", customerNo: "CP00001486", factoryNo: "M00000074", factoryName: "测试上限", thumb, productNo: "DY2026081104", factoryItemNo: "00024584-8", customerItemNo: "00024584-8", productName: "(勿动)测试小图，大图都没有", orderStatus: "报价中", packQty: "2/36(pcs)", quoteCartons: 1, totalQty: 1, currency: "RMB", purchasePrice: "1.00", exFactoryPrice: "1.00", quotePrice: "1.00", amount: "1.00", profit: "0.00", ...specTail },
        { quoteNo: "SQ202608130000000013", customerName: "ghh", customerNo: "CP00001487", factoryNo: "M00000071", factoryName: "112啊", thumb, productNo: "DY2026081105", factoryItemNo: "02656-89", customerItemNo: "02656-89", productName: "(勿动)测试只有大图，没有小图", orderStatus: "报价中", packQty: "2/36(pcs)", quoteCartons: 1, totalQty: 10, currency: "RMB", purchasePrice: "1.00", exFactoryPrice: "1.00", quotePrice: "1.00", amount: "10.00", profit: "0.00", ...specTail },
      ],
    },

    sales: {
      key: "sales",
      file: "02-销售数据报表.html",
      title: "销售数据报表",
      source: "销售订货单",
      note: "表列 44 项，对照飞书「销售数据」。发货/出库/结算状态在单据侧与明细侧各出现一次，按表头原样保留。",
      filters: [
        { placeholder: "订货编号" },
        { placeholder: "报价编号" },
        { placeholder: "客户编号 / 名称" },
        { placeholder: "产品编号 / 名称 / 货号" },
        { placeholder: "厂商编号 / 名称" },
        { type: "select", options: ["币种（全部）", "RMB", "USD"] },
      ],
      statusLabel: "订单状态（多选）",
      statusOptions: [
        { label: "进行中", checked: true },
        { label: "审核中", checked: true },
        { label: "草稿", checked: false },
        { label: "作废", checked: false },
      ],
      groups: [
        { name: "单据主信息", keys: ["orderNo", "quoteNo", "docShipStatus", "docOutboundStatus", "docSettleStatus", "purchaseStatus", "receiveStatus", "inboundStatus", "customerNo", "customerName"] },
        { name: "厂商信息", keys: ["factoryNo", "factoryName"] },
        { name: "产品主信息", keys: ["thumb", "productNo", "factoryItemNo", "customerItemNo", "productName", "orderStatus", "lineShipStatus", "lineOutboundStatus", "lineSettleStatus"] },
        { name: "数量及价格", keys: ["packQty", "orderCartons", "totalQty", "currency", "purchasePrice", "exFactoryPrice", "salePrice", "amount", "profit"] },
        { name: "尺寸重量", keys: sizeKeys },
        { name: "其他属性", keys: attrKeys },
      ],
      columns: [
        { key: "orderNo", label: "订货编号", type: "docLink" },
        { key: "quoteNo", label: "报价编号" },
        { key: "docShipStatus", label: "发货状态", type: "status" },
        { key: "docOutboundStatus", label: "出库状态", type: "status" },
        { key: "docSettleStatus", label: "结算状态", type: "status" },
        { key: "purchaseStatus", label: "采购状态", type: "status" },
        { key: "receiveStatus", label: "收货状态", type: "status" },
        { key: "inboundStatus", label: "入库状态", type: "status" },
        { key: "customerNo", label: "客户编号" },
        { key: "customerName", label: "客户名称" },
        { key: "factoryNo", label: "厂商编号" },
        { key: "factoryName", label: "厂商名称" },
        { key: "thumb", label: "产品图片", type: "thumb" },
        { key: "productNo", label: "产品编号" },
        { key: "factoryItemNo", label: "出厂货号" },
        { key: "customerItemNo", label: "客户货号" },
        { key: "productName", label: "产品名称" },
        { key: "orderStatus", label: "订单状态", type: "status" },
        { key: "lineShipStatus", label: "发货状态", type: "status" },
        { key: "lineOutboundStatus", label: "出库状态", type: "status" },
        { key: "lineSettleStatus", label: "结算状态", type: "status" },
        { key: "packQty", label: "内盒/外箱装量" },
        { key: "orderCartons", label: "订货箱数", type: "num" },
        { key: "totalQty", label: "总数量", type: "num" },
        { key: "currency", label: "币种" },
        { key: "purchasePrice", label: "进货价", type: "amount" },
        { key: "exFactoryPrice", label: "出厂价", type: "amount" },
        { key: "salePrice", label: "销售单价", type: "amount" },
        { key: "amount", label: "总金额", type: "amount" },
        { key: "profit", label: "利润", type: "profit" },
        { key: "productSpec", label: "产品规格" },
        { key: "packSpec", label: "包装规格" },
        { key: "cartonSpec", label: "外箱规格" },
        { key: "volume", label: "体积/材积" },
        { key: "cartonWeight", label: "外箱毛/净重" },
        { key: "productWeight", label: "产品毛/净重" },
        { key: "color", label: "产品颜色" },
        { key: "colorEn", label: "英文颜色" },
        { key: "cert", label: "产品认证" },
        { key: "brand", label: "产品品牌" },
        { key: "material", label: "中文材质" },
        { key: "materialEn", label: "英文材质" },
        { key: "notes", label: "注意事项" },
        { key: "func", label: "功能说明" },
      ],
      rows: [
        { orderNo: "SO00003161", quoteNo: "SQ202608130000000015", docShipStatus: "未出货", docOutboundStatus: "未出库", docSettleStatus: "未结算", purchaseStatus: "采购中", receiveStatus: "待收货", inboundStatus: "未入库", customerNo: "CP00001486", customerName: "海淀", factoryNo: "M00000076", factoryName: "测试一下", thumb, productNo: "DY2026080501", factoryItemNo: "0056565-0", customerItemNo: "0056565-0", productName: "海淀", orderStatus: "进行中", lineShipStatus: "未出货", lineOutboundStatus: "未出库", lineSettleStatus: "未结算", packQty: "2/36(pcs)", orderCartons: 1, totalQty: 20, currency: "RMB", purchasePrice: "8.00", exFactoryPrice: "6.00", salePrice: "6.00", amount: "120.00", profit: "-40.00", ...specTail },
        { orderNo: "SO00003160", quoteNo: "SQ202608130000000014", docShipStatus: "未出货", docOutboundStatus: "未出库", docSettleStatus: "未结算", purchaseStatus: "采购完成", receiveStatus: "待收货", inboundStatus: "未入库", customerNo: "CP00001486", customerName: "海淀", factoryNo: "M00000074", factoryName: "测试上限", thumb, productNo: "DY2026080501", factoryItemNo: "00024584-8", customerItemNo: "00024584-8", productName: "海淀", orderStatus: "进行中", lineShipStatus: "未出货", lineOutboundStatus: "未出库", lineSettleStatus: "未结算", packQty: "2/36(pcs)", orderCartons: 2, totalQty: 20, currency: "RMB", purchasePrice: "8.00", exFactoryPrice: "6.00", salePrice: "6.00", amount: "120.00", profit: "-40.00", ...specTail },
        { orderNo: "SO00003158", quoteNo: "SQ202608130000000013", docShipStatus: "未出货", docOutboundStatus: "未出库", docSettleStatus: "未结算", purchaseStatus: "采购完成", receiveStatus: "收货完成", inboundStatus: "未入库", customerNo: "CP00001486", customerName: "海淀", factoryNo: "M00000071", factoryName: "112啊", thumb, productNo: "DY2026080501", factoryItemNo: "02656-89", customerItemNo: "02656-89", productName: "海淀", orderStatus: "进行中", lineShipStatus: "未出货", lineOutboundStatus: "未出库", lineSettleStatus: "未结算", packQty: "2/36(pcs)", orderCartons: 2, totalQty: 20, currency: "RMB", purchasePrice: "8.00", exFactoryPrice: "6.00", salePrice: "6.00", amount: "120.00", profit: "-40.00", ...specTail },
      ],
    },

    purchase: {
      key: "purchase",
      file: "03-采购数据报表.html",
      title: "采购数据报表",
      source: "采购订货单",
      note: "表列 32 项，对照飞书「采购数据」。厂商编号/名称归在单据主信息（与飞书合并区一致）。",
      filters: [
        { placeholder: "采购编号" },
        { placeholder: "订货编号" },
        { type: "select", options: ["采购类型（全部）", "销售转单", "自主备货"] },
        { placeholder: "厂商编号 / 名称" },
        { placeholder: "产品编号 / 名称 / 货号" },
        { type: "select", options: ["币种（全部）", "RMB", "USD"] },
      ],
      statusLabel: "采购状态（多选）",
      statusOptions: [
        { label: "进行中", checked: true },
        { label: "采购完成", checked: true },
        { label: "草稿", checked: false },
        { label: "作废", checked: false },
      ],
      groups: [
        { name: "单据主信息", keys: ["poNo", "orderNo", "poType", "factoryNo", "factoryName"] },
        { name: "产品主信息", keys: ["thumb", "productNo", "factoryItemNo", "productName", "poStatus"] },
        { name: "数量及价格", keys: ["packQty", "poCartons", "totalQty", "currency", "purchasePrice", "exFactoryPrice", "poPrice", "amount"] },
        { name: "尺寸重量", keys: sizeKeys },
        { name: "其他属性", keys: attrKeys },
      ],
      columns: [
        { key: "poNo", label: "采购编号", type: "docLink" },
        { key: "orderNo", label: "订货编号" },
        { key: "poType", label: "采购类型" },
        { key: "factoryNo", label: "厂商编号" },
        { key: "factoryName", label: "厂商名称" },
        { key: "thumb", label: "产品图片", type: "thumb" },
        { key: "productNo", label: "产品编号" },
        { key: "factoryItemNo", label: "出厂货号" },
        { key: "productName", label: "产品名称" },
        { key: "poStatus", label: "采购状态", type: "status" },
        { key: "packQty", label: "内盒/外箱装量" },
        { key: "poCartons", label: "采购箱数", type: "num" },
        { key: "totalQty", label: "总数量", type: "num" },
        { key: "currency", label: "币种" },
        { key: "purchasePrice", label: "进货价", type: "amount" },
        { key: "exFactoryPrice", label: "出厂价", type: "amount" },
        { key: "poPrice", label: "采购价", type: "amount" },
        { key: "amount", label: "总金额", type: "amount" },
        { key: "productSpec", label: "产品规格" },
        { key: "packSpec", label: "包装规格" },
        { key: "cartonSpec", label: "外箱规格" },
        { key: "volume", label: "体积/材积" },
        { key: "cartonWeight", label: "外箱毛/净重" },
        { key: "productWeight", label: "产品毛/净重" },
        { key: "color", label: "产品颜色" },
        { key: "colorEn", label: "英文颜色" },
        { key: "cert", label: "产品认证" },
        { key: "brand", label: "产品品牌" },
        { key: "material", label: "中文材质" },
        { key: "materialEn", label: "英文材质" },
        { key: "notes", label: "注意事项" },
        { key: "func", label: "功能说明" },
      ],
      rows: [
        { poNo: "PO00004681", orderNo: "SO00003155", poType: "销售转单", factoryNo: "M00000076", factoryName: "测试一下", thumb, productNo: "DY2026080501", factoryItemNo: "", productName: "海淀", poStatus: "进行中", packQty: "2/36(pcs)", poCartons: 10, totalQty: 20, currency: "RMB", purchasePrice: "8.00", exFactoryPrice: "6.00", poPrice: "6.00", amount: "120.00", ...specTail },
        { poNo: "PO00004678", orderNo: "SO00003153", poType: "自主备货", factoryNo: "M00000074", factoryName: "测试上限", thumb, productNo: "DY2026080501", factoryItemNo: "", productName: "海淀", poStatus: "进行中", packQty: "2/36(pcs)", poCartons: 10, totalQty: 20, currency: "RMB", purchasePrice: "8.00", exFactoryPrice: "6.00", poPrice: "6.00", amount: "120.00", ...specTail },
        { poNo: "PO00004677", orderNo: "", poType: "自主备货", factoryNo: "M00000071", factoryName: "112啊", thumb, productNo: "DY2026080501", factoryItemNo: "", productName: "海淀", poStatus: "进行中", packQty: "2/36(pcs)", poCartons: 10, totalQty: 20, currency: "RMB", purchasePrice: "8.00", exFactoryPrice: "6.00", poPrice: "6.00", amount: "120.00", ...specTail },
      ],
    },

    receive: {
      key: "receive",
      file: "04-收货数据报表.html",
      title: "收货数据报表",
      source: "收货单",
      note: "表列 35 项，对照飞书「收货数据」。菜单名采用「收货」，与 REQ / 飞书表一致。",
      filters: [
        { placeholder: "收货编号" },
        { placeholder: "采购编号" },
        { type: "select", options: ["收货类型（全部）", "自主收货", "采购转收货"] },
        { placeholder: "厂商编号 / 名称" },
        { placeholder: "产品编号 / 名称 / 货号" },
        { type: "select", options: ["币种（全部）", "RMB", "USD"] },
      ],
      statusLabel: "收货状态（多选）",
      statusOptions: [
        { label: "待收货", checked: true },
        { label: "收货完成", checked: true },
        { label: "草稿", checked: false },
        { label: "作废", checked: false },
      ],
      groups: [
        { name: "单据主信息", keys: ["cnNo", "poNo", "cnType", "factoryNo", "factoryName"] },
        { name: "产品主信息", keys: ["thumb", "productNo", "factoryItemNo", "productName", "cnStatus", "inboundStatus"] },
        { name: "数量及价格", keys: ["packQty", "totalQty", "receivedCartons", "pendingCartons", "inboundCartons", "currency", "exFactoryPrice", "purchasePrice", "poPrice", "amount"] },
        { name: "尺寸重量", keys: sizeKeys },
        { name: "其他属性", keys: attrKeys },
      ],
      columns: [
        { key: "cnNo", label: "收货编号", type: "docLink" },
        { key: "poNo", label: "采购编号" },
        { key: "cnType", label: "收货类型" },
        { key: "factoryNo", label: "厂商编号" },
        { key: "factoryName", label: "厂商名称" },
        { key: "thumb", label: "产品图片", type: "thumb" },
        { key: "productNo", label: "产品编号" },
        { key: "factoryItemNo", label: "出厂货号" },
        { key: "productName", label: "产品名称" },
        { key: "cnStatus", label: "收货状态", type: "status" },
        { key: "inboundStatus", label: "入库状态", type: "status" },
        { key: "packQty", label: "内盒/外箱装量" },
        { key: "totalQty", label: "总数量", type: "num" },
        { key: "receivedCartons", label: "已收货箱数", type: "num" },
        { key: "pendingCartons", label: "待收货箱数", type: "num" },
        { key: "inboundCartons", label: "入库箱数", type: "num" },
        { key: "currency", label: "币种" },
        { key: "exFactoryPrice", label: "出厂价", type: "amount" },
        { key: "purchasePrice", label: "进货价", type: "amount" },
        { key: "poPrice", label: "采购价", type: "amount" },
        { key: "amount", label: "总金额", type: "amount" },
        { key: "productSpec", label: "产品规格" },
        { key: "packSpec", label: "包装规格" },
        { key: "cartonSpec", label: "外箱规格" },
        { key: "volume", label: "体积/材积" },
        { key: "cartonWeight", label: "外箱毛/净重" },
        { key: "productWeight", label: "产品毛/净重" },
        { key: "color", label: "产品颜色" },
        { key: "colorEn", label: "英文颜色" },
        { key: "cert", label: "产品认证" },
        { key: "brand", label: "产品品牌" },
        { key: "material", label: "中文材质" },
        { key: "materialEn", label: "英文材质" },
        { key: "notes", label: "注意事项" },
        { key: "func", label: "功能说明" },
      ],
      rows: [
        { cnNo: "CN000001631", poNo: "PO00004673", cnType: "自主收货", factoryNo: "M00000063", factoryName: "小鸡厂", thumb, productNo: "DY2026080501", factoryItemNo: "", productName: "海淀", cnStatus: "待收货", inboundStatus: "未入库", packQty: "2/36(pcs)", totalQty: 1600, receivedCartons: 0, pendingCartons: 10, inboundCartons: 0, currency: "RMB", exFactoryPrice: "6.00", purchasePrice: "8.00", poPrice: "6.00", amount: "9600.00", ...specTail },
        { cnNo: "CN000001629", poNo: "PO00004683", cnType: "采购转收货", factoryNo: "M00000064", factoryName: "测试员的", thumb, productNo: "DY2026080501", factoryItemNo: "", productName: "海淀", cnStatus: "待收货", inboundStatus: "未入库", packQty: "2/36(pcs)", totalQty: 1600, receivedCartons: 0, pendingCartons: 10, inboundCartons: 0, currency: "RMB", exFactoryPrice: "6.00", purchasePrice: "8.00", poPrice: "6.00", amount: "9600.00", ...specTail },
        { cnNo: "CN000001627", poNo: "PO00004688", cnType: "采购转收货", factoryNo: "M00000036", factoryName: "海淀", thumb, productNo: "DY2026080501", factoryItemNo: "", productName: "海淀", cnStatus: "待收货", inboundStatus: "未入库", packQty: "2/36(pcs)", totalQty: 1600, receivedCartons: 0, pendingCartons: 10, inboundCartons: 0, currency: "RMB", exFactoryPrice: "6.00", purchasePrice: "8.00", poPrice: "6.00", amount: "9600.00", ...specTail },
      ],
    },

    ship: {
      key: "ship",
      file: "05-发货数据报表.html",
      title: "发货数据报表",
      source: "客户发货单",
      note: "表列 37 项，对照飞书「发货数据」。客户货号在产品主信息中出现两次，按表头原样保留。菜单名采用「发货」。",
      filters: [
        { placeholder: "发货编号" },
        { placeholder: "客户编号 / 名称" },
        { placeholder: "厂商编号 / 名称" },
        { placeholder: "产品编号 / 名称 / 货号" },
        { type: "select", options: ["币种（全部）", "RMB", "USD"] },
      ],
      statusLabel: "发货状态（多选）",
      statusOptions: [
        { label: "已发货", checked: true },
        { label: "未出货", checked: false },
        { label: "草稿", checked: false },
        { label: "作废", checked: false },
      ],
      groups: [
        { name: "单据主信息", keys: ["doNo", "customerNo", "customerName"] },
        { name: "厂商信息", keys: ["factoryNo", "factoryName"] },
        { name: "产品主信息", keys: ["thumb", "productNo", "factoryItemNo", "customerItemNo", "productName", "customerItemNo2", "shipStatus", "outboundStatus"] },
        { name: "数量及价格", keys: ["packQty", "orderCartons", "totalQty", "shipCartons", "outboundCartons", "currency", "exFactoryPrice", "purchasePrice", "salePrice", "amount"] },
        { name: "尺寸重量", keys: sizeKeys },
        { name: "其他属性", keys: attrKeys },
      ],
      columns: [
        { key: "doNo", label: "发货编号", type: "docLink" },
        { key: "customerNo", label: "客户编号" },
        { key: "customerName", label: "客户名称" },
        { key: "factoryNo", label: "厂商编号" },
        { key: "factoryName", label: "厂商名称" },
        { key: "thumb", label: "产品图片", type: "thumb" },
        { key: "productNo", label: "产品编号" },
        { key: "factoryItemNo", label: "出厂货号" },
        { key: "customerItemNo", label: "客户货号" },
        { key: "productName", label: "产品名称" },
        { key: "customerItemNo2", label: "客户货号" },
        { key: "shipStatus", label: "发货状态", type: "status" },
        { key: "outboundStatus", label: "出库状态", type: "status" },
        { key: "packQty", label: "内盒/外箱装量" },
        { key: "orderCartons", label: "订货箱数", type: "num" },
        { key: "totalQty", label: "总数量", type: "num" },
        { key: "shipCartons", label: "发货箱数", type: "num" },
        { key: "outboundCartons", label: "出库箱数", type: "num" },
        { key: "currency", label: "币种" },
        { key: "exFactoryPrice", label: "出厂价", type: "amount" },
        { key: "purchasePrice", label: "进货价", type: "amount" },
        { key: "salePrice", label: "销售单价", type: "amount" },
        { key: "amount", label: "总金额", type: "amount" },
        { key: "productSpec", label: "产品规格" },
        { key: "packSpec", label: "包装规格" },
        { key: "cartonSpec", label: "外箱规格" },
        { key: "volume", label: "体积/材积" },
        { key: "cartonWeight", label: "外箱毛/净重" },
        { key: "productWeight", label: "产品毛/净重" },
        { key: "color", label: "产品颜色" },
        { key: "colorEn", label: "英文颜色" },
        { key: "cert", label: "产品认证" },
        { key: "brand", label: "产品品牌" },
        { key: "material", label: "中文材质" },
        { key: "materialEn", label: "英文材质" },
        { key: "notes", label: "注意事项" },
        { key: "func", label: "功能说明" },
      ],
      rows: [
        { doNo: "DO00000745", customerNo: "CP00001421", customerName: "海定", factoryNo: "M00000076", factoryName: "测试一下", thumb, productNo: "DY2026080501", factoryItemNo: "", customerItemNo: "", productName: "海淀", customerItemNo2: "", shipStatus: "已发货", outboundStatus: "未出库", packQty: "2/36(pcs)", orderCartons: 10, totalQty: 1600, shipCartons: 80, outboundCartons: 0, currency: "RMB", exFactoryPrice: "6.00", purchasePrice: "8.00", salePrice: "6.00", amount: "9600.00", ...specTail },
        { doNo: "DO00000744", customerNo: "CP00001421", customerName: "海定", factoryNo: "M00000074", factoryName: "测试上限", thumb, productNo: "DY2026080501", factoryItemNo: "", customerItemNo: "", productName: "海淀", customerItemNo2: "", shipStatus: "已发货", outboundStatus: "未出库", packQty: "2/36(pcs)", orderCartons: 10, totalQty: 1600, shipCartons: 80, outboundCartons: 0, currency: "RMB", exFactoryPrice: "6.00", purchasePrice: "8.00", salePrice: "6.00", amount: "9600.00", ...specTail },
        { doNo: "DO00000743", customerNo: "CP00001357", customerName: "宣城", factoryNo: "M00000071", factoryName: "112啊", thumb, productNo: "DY2026080501", factoryItemNo: "", customerItemNo: "", productName: "海淀", customerItemNo2: "", shipStatus: "已发货", outboundStatus: "未出库", packQty: "2/36(pcs)", orderCartons: 10, totalQty: 1600, shipCartons: 80, outboundCartons: 0, currency: "RMB", exFactoryPrice: "6.00", purchasePrice: "8.00", salePrice: "6.00", amount: "9600.00", ...specTail },
      ],
    },
  };
})();
